### ISSUE TITLE
Extensions to CustomTriggers

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#37]
Currently, `CustomTriggers` can only add triggers composed of runs of non-space characters.

It should be able to support (limited) regular expressions and triggers containing spaces.

Ideas:
- `!trigger add 'this is a trigger with spaces' 'this is the response'`
- `!trigger add this is a trigger with spaces -> this is the response`
- `!trigger add /match this/ this is a matched response`

**Comment by greenbagels** [comment]
Quick question on code style:

A naive way to solve the problem would be to do this:

```ruby
match /trigger add (\S+.+) -> (\S+.+)/, method: :add_trigger # maps some arbitrary non-whitespace-started string to another
match /trigger add (\S+) (.+)/, method: :add_trigger # this is the line already in the code below:
```
https://github.com/woodruffw/yossarian-bot/blob/c393a727a97db4744fd7a69b83a4305f3fe9eb4c/plugins/custom_triggers/custom_triggers.rb#L45

This appears like it might work prima facie, but it's possible for the following message to match both calls

```text
<greenbagels> !trigger add foo bar -> abcxyz
```
The first call will make the following map
```text
{"foo bar" : "abcxyz"} # first call
{"foo" : "bar -> abcxyz"} #second call
```
I propose adding an `already_added?` variable to the CustomTriggers class that is default set to `false` with `add_trigger` setting it to `true`. In that case, we add conditional predicates to the match calls so that they only execute if a trigger hasn't already been added. I only ask about this because it seems like a bit of a mess to keep track of the `already_added?` state and constantly switch it on and off

**Comment by woodruffw** [comment]
I think it would be best to just go with the new syntax (i.e., `foo -> bar`) and drop support for the old one entirely. That way we don't have to worry about adding extra state like `already_added?`.

This version:

```
match /trigger add (\S+.+) -> (\.+)/, method: :add_trigger
```

seems reasonable to me.

**Comment by greenbagels** [comment]
Sounds good; it's a more robust and clear syntax than the old syntax anyway!
